### ISSUE TITLE
Vectorized ∆R matching

### ISSUE THREAD

**Issue by riga** [columnflow/columnflow#11]
We need to build up expertise on complex vectorized algorithms such as a generic, matrix based matching algorithm between two sets of momentum vectors (in cartesian or lorentz-invariant coordinates).

**Comment by bonanomi** [comment]
Quick out-of-the-box Google search: https://github.com/CoffeaTeam/coffea/issues/395 might be useful

**Comment by artlbv** [comment]
Hi @kramerto @pkausw , I once asked Jim Pivarski how to do that with awk arrays – would this solution help you?
https://github.com/scikit-hep/awkward/discussions/996

I also included an example solution code in the thread. Let me know if I can help!

**Comment by pkausw** [comment]
> Hi @kramerto @pkausw , I once asked Jim Pivarski how to do that with awk arrays – would this solution help you? [scikit-hep/awkward#996](https://github.com/scikit-hep/awkward/discussions/996)
> 
> I also included an example solution code in the thread. Let me know if I can help!

Thanks @artlbv for pointing us to this! Coincidentally, this is exactly what we used because we found it in the source code during the hackathon :D

**Comment by pkausw** [comment]
Just to keep this issue up to date: a first version of the vectorized DeltaR matching is used in the cleaning of fields introduced in PR #37 . I would suggest to keep this issue open though since there is also the matter of doing an actual matching (e.g. of Reco Jets w.r.t. Gen Jets) which requires a different kind of logic
