### ISSUE TITLE
awkward array fails to cast python int/float while normalize in scale.py

### ISSUE THREAD

**Issue by Bogdan-Wiederspan** [columnflow/columnflow#236]
When trying to normalize in [scale.py](https://github.com/columnflow/columnflow/blob/master/columnflow/production/cms/scale.py#L128) the following error will occure:
```
TypeError: while calling

    numpy.divide.__call__(
        <Array [[1.01, 1, ..., 1, 0.984], ...] type='100000 * [var * float3...'>
        1
    )

Error details: no numpy.divide overloads for custom types: NanoCollection, int
```
This error will only occur, when `murf_nominal` is NOT an awkward or numpy array. 
So,  Awkward fails to cast a python int into awkward (instead of using numpy before hand). To fix  set: `murf_norminal = ak.Array((1.))`

**Comment by mafrahm** [comment]
Good catch! I propose we change the solution a bit to preserve the numpy array type 
```
murf_nominal = events.LHEScaleWeight / np.array(1, dtype=np.float32)
```
To fully preserve the array type, we could also do something like this (but I think it's unnecessary):
```
events.LHEScaleWeight / ak.ones_like(events.LHEScaleWeight[:,4])
```

**Comment by pkausw** [comment]
Right, in @Bogdan-Wiederspan 's defense: The idea using an `ak.Array` came from me because I thought it might be nice to stay within the awkward eco system as much as possible. But that's not entirely necessary in this case I guess.

Side note: If we should stick to the eco system, I wouldn't use index `4` explicitely - maybe `0` would be better?
