### ISSUE TITLE
gfal issue with the skeleton/example analysis

### ISSUE THREAD

**Issue by gsaha009** [columnflow/columnflow#291]
Hello CF developers,
While trying to run the `law run cf.ReduceEvents --version dev1 --branch 0` on the skeleton analysis, it got stuck at:|
```
INFO: columnflow.tasks.external - file /store/mc/RunIISummer20UL17NanoAODv9/ST_t-channel_top_4f_InclusiveDecays_TuneCP5_13TeV-powheg-madspin-pythia8/NANOAODSIM/106X_mc2017_realistic_v9-v1/30000/5AA5554D-3FBE-EF48-8375-CE2EF0E54F53.root does exist at fs wlcg_fs_global_redirector
using fs wlcg_fs_global_redirector, stat responded in 12.87 seconds
lfn /store/mc/RunIISummer20UL17NanoAODv9/ST_t-channel_top_4f_InclusiveDecays_TuneCP5_13TeV-powheg-madspin-pythia8/NANOAODSIM/106X_mc2017_realistic_v9-v1/30000/5AA5554D-3FBE-EF48-8375-CE2EF0E54F53.root, size is 1.6 GB
load and open ...

230826 17:32:20 13295 secgsi_ClientDoCert: could not instantiate session cipher using cipher public info from server
WARNING: gfal2 - When trying to clean the destination: Failed to delete file (Unknown error 3011)
230826 17:55:21 13302 secgsi_ClientDoCert: could not instantiate session cipher using cipher public info from server

``` 
Is it some problem with this Quickstart?
Thanks.

Gourab

**Comment by gsaha009** [comment]
I checked with two different datasets and in lxplus7 and 8

**Comment by pkausw** [comment]
Hi @gsaha009 ,

thanks for trying out columnflow, and sorry you encoutered this issue! Here are some follow-up questions to help us track down this error:
- Can you verify that you haven't changed anything in the `law.cfg` file?
- Since you were able to open the lfn for the CalibrateEvents task, I assume you have set up your voms proxy. Are you sure the proxy is still valid by the time you enter the SelectEvents sandbox?

Since the data accessing is handled by law, I'm also tagging @riga here, maybe he has some further insights.

Cheers,
Philip

P.S.: Be aware that there is currently another problem with the skeleton which is documented in issue #290 . We are working on this, but there is also a temparory workaround hinted there. Just so you can keep your momentum after fixing this issue ;)

**Comment by gsaha009** [comment]
Hi @pkausw 

Thanks for your response. I just did the `voms-proxy` again and it works :) :) 
I am quite sure that I did `voms` everytime and I did not change anything in `law.cfg`.
It seemed weird before because the same file was opened in the `calibration` step and then it was not found in the `selection` step.
But, now its working fine.
Thank you so much.

Gourab

**Comment by pkausw** [comment]
Hey @gsaha009 ,

great, glad to hear it works now! I'll mark this issue as closed then. Let us know if you have any additional problems!

Cheers,
Philip

**Comment by riga** [comment]
Hey @gsaha009 ,

Thanks for the detailed report!

Just to follow up on this one, I think you ran into two redirector/site related issues at once. I'm going a bit into depth here since the details are not trivial and I want to note this down for future reference.

### 1. Redirector issue / Rucio inconsistencies

While doing the calibration, the infn redirector reports that it can find the LFN. And indeed, checking manually with `dasgoclient -query "site file=THE_LFN`, it's available on at least 11 european sites. However, in the selection, the same check reports `does not exist at fs wlcg_fs_infn_redirector`, which is inconsistent.

I've personally seen quite a few of these cases since CMS' transition to rucio for their internal file transfers and bookkeeping. The reason for this error is that DAS/DBS and the actual files on storage elements are - at least in these rare cases you observe - not in sync, meaning, the database reports that a file should be available at a site whereas, in truth, it's not. Needless to say, this is a nuisance for analyses, and if this gets more frequent, we should continue writing tickets to the CMS rucio admins and/or have a more robust solution in columnflow (at the end of the day, dealing with the [LFC](https://indico.cern.ch/event/422979/contributions/1036853/attachments/892342/1256376/delgado_LFC_glitetutorial_13150605.pdf) is not too complex).

Until this is fixed / in place, simply rerunning - as you did - often does the trick, especially when the LFN is stored on multiple sites and the next request to the same file ends up at a site where it's actually present. However, in some cases (and we observed this already a couple times in the past) the file is only available **on one site** according to DAS/DBS, but when really accessing the file, it's not. When this happens, there is no way to access the file and one should file an issue with TODO. 


### 2. Server-side xrootd + openssl issue

The LFN is eventually found on the global redirector and served from another site, but you see `could not instantiate session cipher using cipher public info from server`. I think this is due to an incompatibility between xrootd and openssl on the remote site, as reported here: [xrootd/xrootd#2014](https://www.github.com/xrootd/xrootd/issues/2014). We use the newest versions of the two in our client-side stack, but some servers still run old software where the reported issue still exists. I guess this problem will become less frequent over time, and we can't do much about it other then rerunning things.

**Comment by gsaha009** [comment]
Hi @riga 
Thank you very much for this elaborate response.... sounds very logical :)

**Comment by oponcet** [comment]
Hi CF developers,

I'm encountering a similar issue as @gsaha009. I can execute the code once, but most of the time, I encounter the following error:

``` shell
columnflow.tasks.external - file /store/mc/RunIISummer20UL17NanoAODv9/DYJetsToLL_2J_TuneCP5_13TeV-amcatnloFXFX-pythia8/NANOAODSIM/106X_mc2017_realistic_v9-v1/70000/F216E130-4A3E-6742-A3AF-B63CE06676A3.root does exist at fs wlcg_fs_infn_redirector
using fs wlcg_fs_infn_redirector, stat responded in 0.7 seconds
lfn /store/mc/RunIISummer20UL17NanoAODv9/DYJetsToLL_2J_TuneCP5_13TeV-amcatnloFXFX-pythia8/NANOAODSIM/106X_mc2017_realistic_v9-v1/70000/F216E130-4A3E-6742-A3AF-B63CE06676A3.root, size is 661.1 MB
load and open ...
230919 11:17:16 3416430 secgsi_ClientDoCert: could not instantiate session cipher using cipher public info from server
230919 11:17:16 3416431 secgsi_ClientDoCert: could not instantiate session cipher using cipher public info from server
failed (took 4.37 seconds)
```

I plan to work on local NanoAOD to proceed with the development of my code. But I would prefer to work with all the dataset soon. Do you have any new ideas on how to avoid this issue?

I'm using the same git setup as @gsaha009 , and I have verified my `voms-proxy` and `law.cfg`.

Thanks! 

Cheers,

Océane

**Comment by pkausw** [comment]
> Hi CF developers,
> 
> I'm encountering a similar issue as @gsaha009. I can execute the code once, but most of the time, I encounter the following error:
> 
> ```shell
> columnflow.tasks.external - file /store/mc/RunIISummer20UL17NanoAODv9/DYJetsToLL_2J_TuneCP5_13TeV-amcatnloFXFX-pythia8/NANOAODSIM/106X_mc2017_realistic_v9-v1/70000/F216E130-4A3E-6742-A3AF-B63CE06676A3.root does exist at fs wlcg_fs_infn_redirector
> using fs wlcg_fs_infn_redirector, stat responded in 0.7 seconds
> lfn /store/mc/RunIISummer20UL17NanoAODv9/DYJetsToLL_2J_TuneCP5_13TeV-amcatnloFXFX-pythia8/NANOAODSIM/106X_mc2017_realistic_v9-v1/70000/F216E130-4A3E-6742-A3AF-B63CE06676A3.root, size is 661.1 MB
> load and open ...
> 230919 11:17:16 3416430 secgsi_ClientDoCert: could not instantiate session cipher using cipher public info from server
> 230919 11:17:16 3416431 secgsi_ClientDoCert: could not instantiate session cipher using cipher public info from server
> failed (took 4.37 seconds)
> ```
> 
> I plan to work on local NanoAOD to proceed with the development of my code. But I would prefer to work with all the dataset soon. Do you have any new ideas on how to avoid this issue?
> 
> I'm using the same git setup as @gsaha009 , and I have verified my `voms-proxy` and `law.cfg`.
> 
> Thanks!
> 
> Cheers,
> 
> Océane

Hi @oponcet ,

sorry for the late reply. As you already pointed out, this is indeed the same issue that originates from a combination of the two issues that @riga explained above. It's not a cf issue per say, but rather an effect from old software on the remote machines. Of course, it's good to document instances of this error so we can get a feeling of how frequently this happens. Here are some thoughts:

- Does the issue persist if you rerun the command? Depending on the availibilty of the sample you try to access, I could imagine that the global redirector might point you to another site if you rerun the command, which might not have the issue.
- Is it feasible to request to move/copy the sample to another site, possibly even at your home institute? That way, you could avoid having to stream the file in the first place.
- For how many of you datasets does this happen? Is only the DY sample you mention in your message affected?

Beyond these points, there isn't really anything you could do to avoid the issue at the moment imho. But maybe others have other ideas.

Cheers,
Phillip

**Comment by oponcet** [comment]
Hi @pkausw,

Thank you for your response.

- In my case, I would say it's successful only 1 out of 10 tries. So it's very problematic to test my code, especially since it takes a long time to run.
- Regarding the sample access, the easiest option for me would be to use local NanoAOD samples that we have on /eos/ to run only locally and avoid this issue for now. However, I haven't been able to find the right way to do it on ColumnFlow. Perhaps I will open a new issue to inquire about this. It could be beneficial for other people encountering the same problem. It seems to be the easiest solution for now.
- I have tried it on several datasets, and most of the time, it's the same issue.

Note : I'm working on `/afs/` and `lxplus8`

Thanks again for your help. Cheers,

Océane

**Comment by riga** [comment]
Just adding the cross reference here: https://github.com/columnflow/columnflow/issues/301
