### ISSUE TITLE
Difficulty Configuring Columnflow to Access Local NanoAOD

### ISSUE THREAD

**Issue by oponcet** [columnflow/columnflow#301]
Dear Columnflow developers,

I am writing to report an issue related to running on local NanoAOD within the Columnflow framework, following the discussions in issues #291.

I have been attempting to configure Columnflow to operate on a local NanoAOD within the /afs/ directory while needing access to the /eos/ directory. I've made several attempts to modify the configuration in law.cfg, but encountered challenges:

- I attempted to modify `local_fs` by adding the path of my local NanoAOD, but it appears that modifying this path is not allowed.

- I tried modifying `wlcg_fs` with the path of my local NanoAOD, but this resulted in a Proxy error.

- Adding 
```
[local]
 
base: root://eosuser.cern.ch/eos/cms/store/group/phys_tau/TauFW/nano/ 
```
and changing `wlcg_file_systems: local` and `lfn_sources: local`, yet the proxy error persisted.

In addition, I made sure to define a campaign for my dataset.

I apologize if these questions seem naive; I am in the process of familiarizing myself with the software.

Thank you for your assistance in resolving this issue.

Cheers,

Océane 

Working directory : https://github.com/oponcet/HCPToTauTau/tree/tautaudev

**Comment by pkausw** [comment]
Hi @oponcet ,

thank you for your message and apologies for the problems you've had! We're still working on the documentation, so it's quite natural that questions remain open, sorry :/

You can customize the access to lfns by defining your own `get_dataset_lfns` function in your analysis config. You can find an example for this [here](https://github.com/uhh-cms/hh2bbtautau/blob/master/hbt/config/configs_run2ul.py#L738-#L764) . If you don't want to change the wlcg file system paths, you could use e.g. your `local` file system you've defined above in a function like this

```python
def get_dataset_lfns(
            dataset_inst: od.Dataset,
            shift_inst: od.Shift,
            dataset_key: str,
) -> list[str]:
    # destructure dataset_key into parts and create the lfn base directory
    dataset_id, full_campaign, tier = dataset_key.split("/")[1:]
    main_campaign, sub_campaign = full_campaign.split("-", 1)
    lfn_base = law.wlcg.WLCGDirectoryTarget(
                # modify this path according to the directory structure in your local file system.
                # In this example, it's the same structure as for official lfns
                f"/store/{dataset_inst.data_source}/{main_campaign}/{dataset_id}/{tier}/{sub_campaign}/0",
                fs="local",
    )

    # loop though files and interpret paths as lfns
    return [
                lfn_base.child(basename, type="f").path
                for basename in lfn_base.listdir(pattern="*.root")
    ]
```

Set this as the config's `get_dataset_lfns` function as in the example I linked and it should work imho.

Let us know if this resolves the issue and/or if you need more help! :)

Cheers,
Philip

**Comment by oponcet** [comment]
Hi @pkausw, thanks for the answer, it's working :)

Cheers,

Océane

**Comment by riga** [comment]
Hi @oponcet ,

could you also post the stack trace that you see above the one you posted above?
The actual error is raised inside the sandbox, and the error message above is the one thrown outside the sandbox (`Exception: sandbox 'bash::$CF_BASE/sandboxes/venv_columnar_dev.sh' failed with exit code -11, please see the error inside the sandboxed context above for details`).

Thank you!

**Comment by oponcet** [comment]
Hi @riga,

We found the issue, it was just incompatibilities of the HLTs with the local NanoAOD file.

Thanks again for for your assistance.

Cheers,

Océane

**Comment by gsaha009** [comment]
Hi @riga

Since this issue is still open, I would like to add just one point to what @oponcet mentioned. We have noticed that around 70% of the times, if there is any issue like some HLTs/other columns are not found, the error/warning does not appear properly. Even if we try a newer --version, it remains the same. It just shows that sandbox error with exit_code -11. Is there any possible way to get more detailed run log?
Thanks.

Gourab

**Comment by pkausw** [comment]
Hi @gsaha009 ,

it's kind of hard to debug this further with the information in this thread. The exit code doesn't really say a lot about what's going on. There should be a more detailed error message further up in the law output, where the actual error is displayed before it leaves the sandbox you're using. Can you post that?

If it's mainly IO related, you can add this section in your law config

```
[analysis] 
chunked_io_debug: True

```

That should give you a more detailed output.

We are working hard on updating the docs, but that will still need more time since there are various other projects the development team needs to follow up on, sorry :/ Hope this helps!

**Comment by riga** [comment]
> Even if we try a newer --version, it remains the same. It just shows that sandbox error with exit_code -11

@gsaha009 In these instances where this error is reported, is there no additional error shown above still inside the sandbox invocation, i.e., between the two banners

(sandbox start, printed in magenta)

```text
=============================== entering sandbox ===============================
task   : <THE_TASK_ID>
sandbox: bash::$CF_BASE/sandboxes/<THE_SANDBOX_NAME>
================================================================================
```

(the error should be here)

(sandbox end, printed in cyan)
```text
=============================== leaving sandbox ================================
task   : <THE_TASK_ID>
sandbox: bash::$CF_BASE/sandboxes/<THE_SANDBOX_NAME>
================================================================================
```

**Comment by gsaha009** [comment]
Hi @pkausw @riga 

Yes, you are right that if there is some error, it appears before showing the sandbox error. The point I was trying to make that, even if I try with some newer --version, sometimes the error message does not appear in between "entering sandbox" and "leaving sandbox" as described by @riga. Like @oponcet mentioned, we got stuck at the selection task since some HLTs were not available. But, later we found the error message after we tried to run it several times. That was why I was looking for some ways to get a more detailed run log. 
If I encounter similar problem, I will post it with detailed law output.
Thank you very much for your help.

Gourab

**Comment by riga** [comment]
Thanks @gsaha009 !

On a different note, as @pkausw pointed out, also for us some IO related error messages are missing sometimes, or there's even a "Segmentation Error" happening.

We think we know why this happens, but we haven't found a solution yet since it's related to dask_awkward which is still a moving target.

The IO in columnflow is multi-threaded, meaning that chunks of 100k rows (default value) of root or parquet input files are deserialized using multiple, *additional* threads, i.e., the main thread that does the event processing is fed with data by 2 (default value) threads that should be mostly in "I/O wait" state. Since lazy-loading was removed in awkward V2 and conceptionally offloaded to dask_awkward, we are using the latter in the [core of our parquet based IO](https://github.com/columnflow/columnflow/blob/2a76125df911068de4cac980e2d23967b7ec40a3/columnflow/columnar_util.py#L2289).

The issue occurs when an exception is raised in the main thread (i.e. in the processing events with user-code, so most likely due to a "normal" coding error) while the lazy chunk loading happening in the additional threads in the background is in a certain state that interferes with Python's exception handling. A solution could be to catch errors manually in the main thread and to gracefully terminate the IO threads if needed. Alternatively we should update our dask_awkward dependency (probably also pyarrow) and check if this is still an issue in the first place.

In the meantime, if you observe something like this, the only way to see the actual error is to instruct columnflow to not use parallel IO. You can do this with the setting that @pkausw mentioned above, either in your law.cfg, or by setting `LAW__analysis__chunked_io_debug=True` in your environment (all setting can be overwritten by `LAW__section__option=value`).
