### ISSUE TITLE
workflow with condorht fails due to condition: OpSysAndVer == "CentOS7"

### ISSUE THREAD

**Issue by JulesVandenbroeck** [columnflow/columnflow#334]
Hi, I am a new Phd student at UGhent trying out columnflow on the belgian computing system (t2b). The automatic job submission by law/columnflow adds the condition: OpSysAndVer == "CentOS7", however there is not such a variable at our site () so it messes up the jobs. Is there a possibility to customize these conditions in a config of my project?

**Comment by riga** [comment]
Hi @JulesVandenbroeck,

Thanks for opening an issue for this question, that others might have as well :+1:

These rather site-dependent conditions are implemented in the central htcondor workflow:

https://github.com/columnflow/columnflow/blob/3483bcaac6d1e2bd4f3be893bbf5f63725eb3d10/columnflow/tasks/framework/remote.py#L559-L564

In this instance, the "OpsSysAndVer" depends on the value of the `--htcondor-flavor` parameter. Since most remote workflows inherit from this central workflow, one *could* overwrite the method and change the `config.custom_content` which is just a list of key-value pairs.
However, I just pushed a quick change to the master branch that actually removes the default value of this `--htcondor-flavor` parameter so that it's empty now by default, so this version should work for you out-of-the-box. In case you want to set a flavor in the future (e.g. when running on lxplus), you can either set the above mentioned parater, or set and environment variable `CF_HTCONDOR_FLAVOR=...` to the desired value.

Hope this helps!

Feel free to close this issue in case you have no more follow up questions.
