### ISSUE TITLE
"Permission denied" error when attempting to access a file using the Grid File Access Library (GFAL)

### ISSUE THREAD

**Issue by Payal7890** [columnflow/columnflow#478]
Hello currently I am running my selection script using mttbar_trigger_study repository (https://gitlab.cern.ch/dsavoiu/mttbar_trigger_study). Every time my jobs are failing due to the "Permission Denied" error. This is one of the output log files:  /nfs/dust/cms/user/payalroy/mttbar_trigger_study/data/tgs_store/analysis_tgs/cf.CalibrateEvents/run2_2017_nano_v9/tt_dl_powheg/nominal/calib__default/v1/stdall_85To86.txt

It would be of great help if I can get a lead. Nothing is running right now.

**Comment by riga** [comment]
It looks like the issue comes from the global xrd redirector (``) that fails to provide the requested lfn. These issues can sometimes occur but should be resolved after some time.

In the meantime, I would suggest to also add the US redirector to your `law.cfg` file:

```init
[wlcg_fs_us_redirector]

base:  root://cmsxrootd.fnal.gov/
use_cache: $CF_WLCG_USE_CACHE
cache_root: $CF_WLCG_CACHE_ROOT
cache_cleanup: $CF_WLCG_CACHE_CLEANUP
cache_max_size: 15GB
cache_global_lock: True
cache_mtime_patience: -1
```

(just like you will find it there for the global and infn redirectors)

With that, you should update the `lfn_sources` list in https://gitlab.cern.ch/dsavoiu/mttbar_trigger_study/-/blob/master/law.cfg?ref_type=heads#L74 to

`lfn_sources: wlcg_fs_infn_redirector, wlcg_fs_us_redirector, wlcg_fs_desy_dcache, wlcg_fs_global_redirector`

Hope this helps!

**Comment by Payal7890** [comment]
Makes sense, thank you so much for helping me out. It's clear now.

**Comment by Payal7890** [comment]
Right, that solves the problem. But in this repo, /nfs/dust/cms/user/payalroy/mttbar/law.cfg, I have added US redirector and using gsiftp as well, jobs are continuously failing (running fine locally). Here is one of the output log file for instance, /nfs/dust/cms/user/payalroy/mttbar/data/mtt_store/analysis_mtt/cf.CalibrateEvents/run2_2017_nano_v9/tt_dl_powheg/nominal/calib__skip_jecunc/v14/stdall_5To6.txt.

Is there any other way out to solve this issue? I look forward to hearing from you. Thank you again.
